// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tueobdgcahbccqznnhjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR1ZW9iZGdjYWhiY2Nxem5uaGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODI1NTYsImV4cCI6MjA1OTk1ODU1Nn0.Hk9dxqu_WPZa7Vsn-PBO7kA2BRM39qxNQr1-6rNY4QA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);